### ISSUE TITLE
Release 7.17.x versions on conda-forge

### ISSUE THREAD

**Issue by sethmlarson** [conda-forge/elasticsearch-feedstock#73]
### Comment:

Currently conda-forge seems to have trouble with the release structure we use at Elastic, maintaining and releasing two major release streams at a time. See: https://github.com/elastic/elasticsearch-py/issues/1980

Going to cc @conda-forge/core for a bit of help here, what's the best way to implement this situation for a feedstock?

**Comment by jaimergp** [comment]
Hi! You can create a branch for the 7.x series and merge the relevant PRs to that branch instead of `main`.

**Comment by sethmlarson** [comment]
Thanks for the reply @jaimergp, is there a way to configure automated upgrades on that branch or it would have to be a manual process?

**Comment by jaimergp** [comment]
I am afraid it has to be manual for now :(

**Comment by sethmlarson** [comment]
I've pushed a branch with the updated recipe, this is all that's needed and Conda press will do the rest? https://github.com/conda-forge/elasticsearch-feedstock/tree/7.x

**Comment by jaimergp** [comment]
Unfortunately the CI failed. From now on, you can create fork-PRs targeting `7.x` to address issues (direct to push to the feedstock is not recommended because it _always_ triggers an upload).

**Comment by jaimergp** [comment]
See https://github.com/conda-forge/elasticsearch-feedstock/pull/74

**Comment by jaimergp** [comment]
Packages available https://anaconda.org/conda-forge/elasticsearch/files?version=7.17.6!
